language: go
go:
  - master
  - stable
  - "1.11"
  - "1.10"
  - "1.9"
  - "1.8"
install:
  - go get -t ./...
  - go get github.com/mattn/goveralls
  - sudo apt-get install -y gpsbabel
script:
  - goveralls -v -service=travis-ci
